### ISSUE TITLE
Command line error with maxquant

### ISSUE THREAD

**Issue by bobturneruk** [Mesnage-Org/pgfinder#164]
When I run (e.g.):

```
find_pg --input_file data/maxquant_test_data.txt --masses_file data/masses/e_coli_monomer_masses.csv --mod_list "['Sodium', 'Potassium']"
```

I get:

```
[Wed, 07 Jun 2023 09:27:04] [INFO    ] [pgfinder] Default configuration file loaded.
[Wed, 07 Jun 2023 09:27:04] [INFO    ] [pgfinder] Updated config config[input_file] : data/ftrs_test_data.ftrs > /home/bobturner/pgfinder-nextflow/data/maxquant_test_data.txt 
[Wed, 07 Jun 2023 09:27:04] [INFO    ] [pgfinder] Updated config config[masses_file] : data/masses/e_coli_monomer_masses.csv > /home/bobturner/pgfinder-nextflow/data/masses/e_coli_monomer_masses.csv 
[Wed, 07 Jun 2023 09:27:04] [INFO    ] [pgfinder] Updated config config[mod_list] : ['none'] > ['[', "'", 'S', 'o', 'd', 'i', 'u', 'm', "'", ',', ' ', "'", 'P', 'o', 't', 'a', 's', 's', 'i', 'u', 'm', "'", ']'] 
[Wed, 07 Jun 2023 09:27:04] [INFO    ] [pgfinder] NB : All warnings have been turned off for this run.
[Wed, 07 Jun 2023 09:27:04] [INFO    ] [pgfinder] Mass spectroscopy file loaded from : /home/bobturner/pgfinder-nextflow/data/maxquant_test_data.txt
[Wed, 07 Jun 2023 09:27:04] [INFO    ] [pgfinder] Theoretical masses loaded from     : /home/bobturner/pgfinder-nextflow/data/masses/e_coli_monomer_masses.csv
[Wed, 07 Jun 2023 09:27:04] [INFO    ] [pgfinder] PPM Tolerance                      : 10
[Wed, 07 Jun 2023 09:27:04] [INFO    ] [pgfinder] Time Delta                         : 0.5
[Wed, 07 Jun 2023 09:27:04] [INFO    ] [pgfinder] Filtering theoretical masses by observed masses
[Wed, 07 Jun 2023 09:27:04] [INFO    ] [pgfinder] Building custom search file
[Wed, 07 Jun 2023 09:27:04] [INFO    ] [pgfinder] Generating variants
[Wed, 07 Jun 2023 09:27:04] [INFO    ] [pgfinder] Matching
[Wed, 07 Jun 2023 09:27:04] [INFO    ] [pgfinder] Cleaning data
[Wed, 07 Jun 2023 09:27:04] [INFO    ] [pgfinder] Difference in PPM calculated.
[Wed, 07 Jun 2023 09:27:04] [INFO    ] [pgfinder] No ^Na+ found
[Wed, 07 Jun 2023 09:27:04] [INFO    ] [pgfinder] No ^K+ found
[Wed, 07 Jun 2023 09:27:04] [INFO    ] [pgfinder] No ^m found
[Wed, 07 Jun 2023 09:27:04] [INFO    ] [pgfinder] Processing complete!
Traceback (most recent call last):
  File "/home/bobturner/miniconda3/envs/pgfinder/bin/find_pg", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/bobturner/miniconda3/envs/pgfinder/lib/python3.11/site-packages/pgfinder/find_pg.py", line 147, in main
    process_file(
  File "/home/bobturner/miniconda3/envs/pgfinder/lib/python3.11/site-packages/pgfinder/find_pg.py", line 99, in process_file
    dataframe_to_csv_metadata(
  File "/home/bobturner/miniconda3/envs/pgfinder/lib/python3.11/site-packages/pgfinder/pgio.py", line 305, in dataframe_to_csv_metadata
    output_dataframe = long_to_wide(df=output_dataframe.copy())
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bobturner/miniconda3/envs/pgfinder/lib/python3.11/site-packages/pgfinder/pgio.py", line 380, in long_to_wide
    keep_other = df[keep_columns].copy()
                 ~~^^^^^^^^^^^^^^
  File "/home/bobturner/miniconda3/envs/pgfinder/lib/python3.11/site-packages/pandas/core/frame.py", line 3767, in __getitem__
    indexer = self.columns._get_indexer_strict(key, "columns")[1]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bobturner/miniconda3/envs/pgfinder/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 5876, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "/home/bobturner/miniconda3/envs/pgfinder/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 5938, in _raise_if_missing
    raise KeyError(f"{not_found} not in index")
KeyError: "['Ion count', 'Charge state', 'XIC start (min)', 'XIC end (min)'] not in index"
```

Not sure if I'm passing the mod_list correctly, but I don't get the error with an FTRS file.

Need to see if the same problem occurs in the notebook.

**Comment by TheLostLambda** [comment]
Problem here looks like the format conversion added by @ns-rse (I think) is expecting columns that are only present in FTRS files. I'll see what an updated version of MaxQuant output looks like, and we'll shoot to standardize on that as much as is possible!

**Comment by bobturneruk** [comment]
Solution is to drop official byos support and make clear which version of maxquant should be used. Maxquant is an open source tool in wide use.

**Comment by bobturneruk** [comment]
Users might benefit from some instructions on how to get their data into maxquant.
