### ISSUE TITLE
Fix Jupyter notebook

### ISSUE THREAD

**Issue by smesnage** [Mesnage-Org/pgfinder#98]
Published link (see below) no longer works. It says something about the package that it tries to install not being the right one.
Can't copy/paste the error message, all I get at the end is     **500 : Internal Server Error**

https://mybinder.org/v2/gh/Mesnage-Org/PGFinder/master?urlpath=tree/pgfinder_interactive.ipynb

**Comment by bobturneruk** [comment]
I think this may be intermittent and on myBinder. @ns-rse please will you take a look?

**Comment by ns-rse** [comment]
Just started investigating, the log from launching is below, it builds ok and says its launching...

```
Pushing image
Pushing image
Pushing image
Pushing image
Pushing image
Pushing image
Pushing image
Pushing image
Pushing image
Pushing image
Pushing image
Pushing image
Pushing image
Successfully pushed gesiscss/binder-r2d-g5b5b759-mesnage-2dorg-2dpgfinder-975c40:5e005052c34e00de27ce16c965ea7d33f76a0399Built image, launching...
Launching server...
Server requested
2022-06-13T08:18:27Z [Normal] Successfully assigned bhub-ns/jupyter-mesnage-2dorg-2dpgfinder-2drx4impgc to spko-css-app03
2022-06-13T08:18:27Z [Normal] Successfully assigned bhub-ns/jupyter-mesnage-2dorg-2dpgfinder-2drx4impgc to spko-css-app03
2022-06-13T08:18:13Z [Normal] Started container block-cloud-metadata
2022-06-13T08:18:27Z [Normal] Successfully assigned bhub-ns/jupyter-mesnage-2dorg-2dpgfinder-2drx4impgc to spko-css-app03
2022-06-13T08:18:27Z [Normal] Successfully assigned bhub-ns/jupyter-mesnage-2dorg-2dpgfinder-2drx4impgc to spko-css-app03
```

**Comment by ns-rse** [comment]
I've now experienced `500: Internal Server Error` at the outset of trying to launch (i.e. the above launch and log doesn't even begin). Which further supports the idea that its a problem with [mybinder.org](https://mybinder.org).

I tried setting up a new instance from the above link, specifying the repository, branch (`master`) and Notebook (`pgfinder_interactive.ipynb`) with the same result.

Digging into the Binder documentation I found there is an [events archive](https://mybinder-sre.readthedocs.io/en/latest/analytics/events-archive.html) which includes links to the [logs of all events](https://archive.analytics.mybinder.org) and code on how to download these into Python. So we can look at the logs for today (`2022-06-13`) and see what has occurred on their server side...

```python
import pandas as pd

# Set variables
date = "2022-06-13"
pgfinder_repo = "Mesnage-Org/PGFinder/master"

# Load data
binder_log = pd.read_json(f"https://archive.analytics.mybinder.org/events-{date}.jsonl", lines=True)

# Filter for this repo on the master branch
binder_log.loc[binder_log["spec"] == pgfinder_repo].T

                                                  433
timestamp                   2022-06-13 01:50:00+00:00
schema                   binderhub.jupyter.org/launch
version                                             5
provider                                       GitHub
spec                      Mesnage-Org/PGFinder/master
ref          5e005052c34e00de27ce16c965ea7d33f76a0399
status                                        success
build_token                                      True
origin                               gke.mybinder.org
```

Only one instance appears to have successfully launched, which somewhat aligns with our current experience.

In tweaking the `README.md` to include links to different versions of the Notebooks on Thursday I launched a number of different instances so lets look for those in the logs.

```python
date = "2022-06-09"
pgfinder_repo = "Mesnage-Org/PGFinder/master"

# Load data
binder_log_20220609 = pd.read_json(f"https://archive.analytics.mybinder.org/events-{date}.jsonl", lines=True)

# Filter for this repo on the master branch
binder_log_20220609.loc[binder_log_20220609["spec"] == pgfinder_repo].T
                                                 5497                                      7128
timestamp                   2022-06-09 13:24:00+00:00                 2022-06-09 16:06:00+00:00
schema                   binderhub.jupyter.org/launch              binderhub.jupyter.org/launch
version                                             5                                         5
provider                                       GitHub                                    GitHub
spec                      Mesnage-Org/PGFinder/master               Mesnage-Org/PGFinder/master
ref          ba8e9ea52ffea835654ef439946e8d80d9259b3e  b12324159e67511cd795fc635207b09a752eca05
status                                        success                                   success
build_token                                      True                                      True
origin                             gesis.mybinder.org                        gesis.mybinder.org
```

Two successful launches of the `master` branch. Lets check and see if the 0.1.0 branch launched...

```python 
pgfinder_repo = "Mesnage-Org/PGFinder/v0.1.0"
binder_log_20220609.loc[binder_log_20220609["spec"] == pgfinder_repo].T
                                                 5660                                      7087
timestamp                   2022-06-09 13:41:00+00:00                 2022-06-09 16:02:00+00:00
schema                   binderhub.jupyter.org/launch              binderhub.jupyter.org/launch
version                                             5                                         5
provider                                       GitHub                                    GitHub
spec                      Mesnage-Org/PGFinder/v0.1.0               Mesnage-Org/PGFinder/v0.1.0
ref          8cffb481a88f9e4377b32514c86903af4515fbdf  8cffb481a88f9e4377b32514c86903af4515fbdf
status                                        success                                   success
build_token                                      True                                      True
origin                               gke.mybinder.org                          gke.mybinder.org
```

Again two successful launches.

At the moment I'm not sure what is going on here because on "our" side of things nothing has changed between Thursday and today

* The underlying `pgfinder` code hasn't been modified
* The code that installs the package and is run before the Notebook can launch hasn't been touched
* The way in which the Binder version of the Jupyter Notebook is launched has not changed).

...all of which points to it being an error on the Binder side of things. I'll keep an eye on things and test them again a little later to see if it has resolved itself.

**Comment by ns-rse** [comment]
For sanity I've checked in different browsers and it fails across the following...

* Opera 88.0.4412.27
* Firefox 101.0.1
* Vivaldi 5.3.2679.55

There are some errors when setting up the Notebook related to Jinja2 and the hiding of code using `contextfilter` and `hide_code` which fail to import, but the last release of [Jinja2 was 2022-04-28](https://jinja.palletsprojects.com/en/3.1.x/changes/) and nothing recently over the weekend that might have broken things. Its something to do with hiding code (based on the modules that are failing to import) but I've started the notebooks locally and can not see any code relating to such actions. Perhaps its something to do with the [voila](https://github.com/voila-dashboards/voila) package that seems to be loaded and used to turn notebooks into standalone web applications, these appear to be pulled in by the `requirements.txt` file.

```python
�[91mTraceback (most recent call last):
  File "/srv/conda/envs/notebook/bin/jupyter-contrib", line 8, in <module>
    sys.exit(main())
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/jupyter_core/application.py", line 264, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/traitlets/config/application.py", line 662, in launch_instance
    app = cls.instance(**kwargs)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/traitlets/config/configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/jupyter_contrib_core/application.py", line 27, in __init__
    self._refresh_subcommands()
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/jupyter_contrib_core/application.py", line 43, in _refresh_subcommands
    get_subcommands_dict = entrypoint.load()
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2471, in load
    return self.resolve()
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2477, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/jupyter_contrib_nbextensions/application.py", line 15, in <module>
    from jupyter_contrib_nbextensions.install import (
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/jupyter_contrib_nbextensions/install.py", line 12, in <module>
    import latex_envs
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/latex_envs/__init__.py", line 3, in <module>
    from . import latex_envs
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/latex_envs/latex_envs.py", line 20, in <module>
    from nbconvert.exporters.exporter import Exporter
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbconvert/__init__.py", line 4, in <module>
    from .exporters import *
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbconvert/exporters/__init__.py", line 3, in <module>
    from .html import HTMLExporter
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbconvert/exporters/html.py", line 12, in <module>
    from jinja2 import contextfilter
ImportError: cannot import name 'contextfilter' from 'jinja2' (/srv/conda/envs/notebook/lib/python3.7/site-packages/jinja2/__init__.py)
�[0m�[91mCopying: hide_code -> /srv/conda/envs/notebook/share/jupyter/nbextensions/hide_code
�[0m�[91mTraceback (most recent call last):
  File "/srv/conda/envs/notebook/bin/jupyter-nbextension", line 10, in <module>
    sys.exit(main())
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/jupyter_core/application.py", line 264, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/traitlets/config/application.py", line 664, in launch_instance
    app.start()
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/nbextensions.py", line 980, in start
    super().start()
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/jupyter_core/application.py", line 253, in start
    self.subapp.start()
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/nbextensions.py", line 708, in start
    self.install_extensions()
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/nbextensions.py", line 687, in install_extensions
    **kwargs
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/nbextensions.py", line 191, in install_nbextension
    _maybe_copy(src, full_dest, logger=logger)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/nbextensions.py", line 1038, in _maybe_copy
    shutil.copy2(src, dest)
  File "/srv/conda/envs/notebook/lib/python3.7/shutil.py", line 266, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/srv/conda/envs/notebook/lib/python3.7/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'hide_code'
�[0m�[91mEnabling notebook extension hide_code...
�[0m�[91m      - Validating: problems found:
        - require? �[31m X�[0m hide_code
�[0m�[91mEnabling: hide_code
- Writing config: /srv/conda/envs/notebook/etc/jupyter
�[0m�[91m    - Validating...
�[0m�[91mError loading server extension hide_code
     �[31m X�[0m is hide_code importable?
�[0m�[91mTraceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/hide_code/__init__.py", line 1, in <module>
    from hide_code.hide_code_html_exporter import HideCodeHTMLExporter
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/hide_code/hide_code_html_exporter.py", line 6, in <module>
    from nbconvert.exporters.html import HTMLExporter
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbconvert/__init__.py", line 4, in <module>
    from .exporters import *
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbconvert/exporters/__init__.py", line 3, in <module>
    from .html import HTMLExporter
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbconvert/exporters/html.py", line 12, in <module>
    from jinja2 import contextfilter
ImportError: cannot import name 'contextfilter' from 'jinja2' (/srv/conda/envs/notebook/lib/python3.7/site-packages/jinja2/__init__.py)
```

Might be some of these packages that have been recently updated (e.g. jupyterlab was updated 2022-06-07) so I'll check these tomorrow.

**Comment by ns-rse** [comment]
There is something strange going on here, a search for the error `ImportError: cannot import name 'contextfilter' from 'jinja2'` led me to [this thread](https://github.com/d2l-ai/d2l-book/issues/46) where the same error cropped up.

In the log-files from launching the Notebook where all dependencies are installed we have the following...

```
  Attempting uninstall: nbconvert
    Found existing installation: nbconvert 6.4.5
    Uninstalling nbconvert-6.4.5:
      Successfully uninstalled nbconvert-6.4.5
  Attempting uninstall: ipykernel
    Found existing installation: ipykernel 6.12.1
    Uninstalling ipykernel-6.12.1:
      Successfully uninstalled ipykernel-6.12.1
  Attempting uninstall: jupyter-server
    Found existing installation: jupyter-server 1.16.0
    Uninstalling jupyter-server-1.16.0:
      Successfully uninstalled jupyter-server-1.16.0
[91mERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
nbclient 0.5.13 requires traitlets>=5.0.0, but you have traitlets 4.3.3 which is incompatible.
[0mSuccessfully installed argcomplete-2.0.0 cycler-0.11.0 fonttools-4.33.3 hide_code-0.6.0 ipykernel-6.4.2 ipysheet-0.5.0 jupyter-1.0.0 jupyter-console-6.4.3 jupyter-contrib-core-0.3.3 jupyter-highlight-selected-word-0.2.0 jupyter-latex-envs-1.4.6 jupyter-nbextensions-configurator-0.4.1 jupyter-server-1.13.2 jupyter_contrib_nbextensions-0.5.1 kiwisolver-1.4.3 lxml-4.9.0 matplotlib-3.5.2 nbconvert-5.6.1 numpy-1.21.6 pandas-1.3.5 pdfkit-1.0.0 pgfinder-0.0.2 pillow-9.1.1 pysqlite3-0.4.7 pyyaml-6.0 qtconsole-5.3.1 qtpy-2.1.0 traitlets-4.3.3
```

Which shows that initially `nbconvert-6.4.5` is installed but it is then _uninstalled_ in favour of `nbconvert-6.4.5`. An issue on [nbconvert](https://github.com/jupyter/nbconvert/issues/1742) contains a [post from one of the contributors](https://github.com/jupyter/nbconvert/issues/1742#issuecomment-1084367167) that Jinja2, on which `nbconvert` depends heavily, deprecated a number of modules which is causing problems for them and recommends against pinning versions.

For our problem though the question is why `nbconvert-6.4.5` is being removed in favour of `nbconvert-5.6.1`. Reading through the log (again) we see that there is the following line...

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
nbclient 0.5.13 requires traitlets>=5.0.0, but you have traitlets 4.3.3 which is incompatible.
```

Ok so why is `traitlets-4.3.3` being pulled in? The first occurrence in the log of `traitlets` is on line 182, preceeded by lines about the `notebook` version being satisfied as a depedency from `hide_code>=0.5.2`...

```
Requirement already satisfied: notebook>=6.0 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from hide_code>=0.5.2->-r requirements.txt (line 2)) (6.4.10)
Collecting traitlets<5.0
  Downloading traitlets-4.3.3-py2.py3-none-any.whl (75 kB)
```

We might be getting somewhere as we have a pointer to something we can control, i.e. line 2 of `requirements.txt`.

The latest version of `hide_code` is `0.6.0` released December 2020 (see [hide_code on PyPi](https://pypi.org/project/hide-code/)), lets check if that is installed...

```
Collecting hide_code>=0.5.2
  Downloading hide_code-0.6.0.tar.gz (62 kB)
     .................................
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
```

It is, so we can't do anything there as we're already using the most recent version. But if we look at the [hide_code issues on GitHub](https://github.com/kirbs-/hide_code/issues) we find a host of reports with similar problems...

* [#101 | Support for recent nbconvert and traitlets](https://github.com/kirbs-/hide_code/issues/101)
* [#98 | Traitlets too old for Jupyter Server](https://github.com/kirbs-/hide_code/issues/98)
* [92 | Export issue (jinja2.exceptions.TemplateNotFound: hide_code_full.tpl)](https://github.com/kirbs-/hide_code/issues/92)

The oldest was closed in 2020 with the "fix" being to pegging the dependency for `hide_code` to be `nbconvert>=5.0,<6` (see [commit](https://github.com/kirbs-/hide_code/commit/4ca4e6e55ba8b699b4dc49f663c894edd5bf7c9b)).

I've added our voice to the most recent issue [#101 | Support for recent nbconvert and traitlets](https://github.com/kirbs-/hide_code/issues/101). 

But then I went back to pip's error...

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
nbclient 0.5.13 requires traitlets>=5.0.0, but you have traitlets 4.3.3 which is incompatible.
```

What is the most recent version of `nbclient`? Checking on [PyPi its 0.6.4](https://pypi.org/project/nbclient/), I wonder what happens if I specify a minimum requirement for `nbclient>=0.6.4` in our `requirements.txt` then, will it upgrade all the other things?

Having done so I've given it a whirl and tried [launching the interactive notebook off of the commit 73adc7d](https://mybinder.org/v2/gh/Mesnage-Org/PGFinder/73adc7d?urlpath=tree/pgfinder_interactive.ipynb) (<< Follow this link, it should launch the notebook and work, it just has for me!).

The current situation of being dependent on Binder, the configuration of which is in many places outside of our control as it appears many packages are pulled in automatically in the virtual environments they launch, is not ideal. This has taken a couple of hours of head scratching and reading logs to work out which is time I could have spent on #7 and #80
